export const lotteryTypes = {
    stone: {
        color: "bg-[#f3ffca]",
        size: "text-xl",
        selectColor: "bg-green-400",
        boColor: "border-[#6c3b2a]",
        textColor: "text-[#6c3b2a]",
        price: "0.25",
        prize: "20 WLD",
        bgColor: "bg-[#d89a76]",
        backgroundImage: "/images/bg_quarzt.jpg",
        titleImage: "/images/title_quartz.png",
    },
    quartz: {
        color: "bg-[#f3ffca]",
        size: "text-xl",
        selectColor: "bg-green-400",
        boColor: "border-green-600",
        textColor: "text-green-600",
        price: "0.5",
        prize: "40 WLD",
        bgColor: "bg-green-200",
        backgroundImage: "/images/bg_quarzt.jpg",
        titleImage: "/images/title_quartz.png",
    },
    citrine: {
        color: "bg-[#ffefbd]",
        size: "text-xl",
        selectColor: "bg-[#ff6c01]",
        boColor: "border-[#ff6c01]",
        textColor: "text-black",
        price: "1",
        prize: "80 ETH",
        bgColor: "bg-yellow-200",
        backgroundImage: "/images/bg_citrine.jpg",
        titleImage: "/images/title_citrine.png",
    },
    amethyst: {
        color: "bg-[#f7ecff]",
        size: "text-lg",
        selectColor: "bg-[#903eca]",
        boColor: "border-[#903eca]",
        textColor: "text-purple-600",
        price: "3",
        prize: "240 WLD",
        bgColor: "bg-purple-200",
        backgroundImage: "/images/bg_amethyst.png",
        titleImage: "/images/title_amethyst.png",
    },
    sapphire: {
        color: "bg-[#d5f0ff]",
        size: "text-xl",
        selectColor: "bg-[#3554f7]",
        boColor: "border-[#3554f7]",
        textColor: "text-blue-600",
        price: "5",
        prize: "400 WLD",
        bgColor: "bg-blue-200",
        backgroundImage: "/images/bg_sapphire.png",
        titleImage: "/images/title_sapphire.png",
    },
    diamond: {
        color: "bg-[#fff5fb]",
        size: "text-xl",
        selectColor: "bg-[#4b002a]",
        boColor: "border-[#4b002a]",
        textColor: "text-black drop-shadow-[0_0_5px_white]",
        price: "10",
        prize: "80 WLD",
        bgColor: "bg-gray-200",
        backgroundImage: "/images/bg_diamond.png",
        titleImage: "/images/title_diamond.png",
    },
};