export const lotteryTypes = {
    quartz: {
        color: "bg-[#f3ffca]",
        size: "text-xl",
        selectColor: "bg-green-400",
        boColor: "border-green-600",
        textColor: "text-green-600",
        price: "0.00005",
        prize: "0.004 ETH",
        bgColor: "bg-green-200",
        backgroundImage: "/images/bg_quarzt.jpg",
        titleImage: "/images/title_quartz.png",
    },
    citrine: {
        color: "bg-[#ffefbd]",
        size: "text-xl",
        selectColor: "bg-[#ff6c01]",
        boColor: "border-[#ff6c01]",
        textColor: "text-black",
        price: "0.0001",
        prize: "0.008 ETH",
        bgColor: "bg-yellow-200",
        backgroundImage: "/images/bg_citrine.jpg",
        titleImage: "/images/title_citrine.png",
    },
    amethyst: {
        color: "bg-[#f7ecff]",
        size: "text-lg",
        selectColor: "bg-[#903eca]",
        boColor: "border-[#903eca]",
        textColor: "text-purple-600",
        price: "0.0003",
        prize: "0.024 ETH",
        bgColor: "bg-purple-200",
        backgroundImage: "/images/bg_amethyst.png",
        titleImage: "/images/title_amethyst.png",
    },
    saphire: {
        color: "bg-[#d5f0ff]",
        size: "text-xl",
        selectColor: "bg-[#3554f7]",
        boColor: "border-[#3554f7]",
        textColor: "text-blue-600",
        price: "0.0005",
        prize: "0.04 ETH",
        bgColor: "bg-blue-200",
        backgroundImage: "/images/bg_sapphire.png",
        titleImage: "/images/title_sapphire.png",
    },
    diamond: {
        color: "bg-[#fff5fb]",
        size: "text-xl",
        selectColor: "bg-[#4b002a]",
        boColor: "border-[#4b002a]",
        textColor: "text-black drop-shadow-[0_0_5px_white]",
        price: "0.001",
        prize: "0.08 ETH",
        bgColor: "bg-gray-200",
        backgroundImage: "/images/bg_diamond.png",
        titleImage: "/images/title_diamond.png",
    },
};